image: node:10.1.0

cache:
  paths:
  - node_modules/
  - .yarn

stages:
  - build
  - test

before_script:
  - yarn config set cache-folder .yarn
  - yarn install

build:
  stage: build
  tags: node
  script: yarn run build

test:
  stage: test
  tags: node
  script: yarn test
