image: node:10.1.0

cache:
  paths:
  - node_modules/
  - .yarn

stages:
  - build
  - test

Build:
  stage: build
  tags: node
  before_script:
   - yarn config set cache-folder .yarn
   - yarn install
  script:
   - yarn run build

Test:
  stage: test
  tags: node
  before_script:
   - yarn config set cache-folder .yarn
   - yarn install
  script:
   - yarn test
