image: node:10.1.0

stages:
  - build
  - test

before_script:
- npm install

build_node6144:
  image: node:6.14.4
  stage: build
  script: npm run build

build_node8120:
  image: node:8.12.0
  stage: build
  script: npm run build

build_node10110:
  image: node:10.11.0
  stage: build
  script: npm run build

test_node6144:
  image: node:6.14.4
  stage: test
  script: npm test

test_node8120:
  image: node:8.12.0
  stage: test
  script: npm test

test_node10110:
  image: node:10.11.0
  stage: test
  script: npm test
