language: node_js
node_js:
  - "10.1.0"

services:
  - docker

before_install:
  - rm -rf dist/*
  - npm install -q

script:
  - npm run build
  - npm run test

notifications:
  email:
    on_success: never
