language: node_js
node_js:
  - "6.14.4"
  - "8.12.0"
  - "10.11.0"

cache:
  directories:
    - "node_modules"

services:
  - docker

before_install:
  - sudo apt-get install libgif-dev
  - rm -rf dist/*
  - npm install -q

script:
  - npm run build
  - npm run test

after_success:
  - pip install --user codecov
  - codecov --file coverage/lcov.info --disable search

notifications:
  email:
    on_success: never
