language: node_js
node_js:
  - "6.11.4"

services:
  - docker

before_install:
  - rm -rf dist/*
  - npm install -q

script:
  - npm run build
  - npm test

notifications:
  email:
    on_success: never
